### ISSUE TITLE
User Specified Gem Templates?

### ISSUE THREAD

**Issue by TheNotary** [jhsu802701/generic_gem#1]
Any chance you could turn this into a gem where users can define their own templates for gems?  For instance, I would love to have a template for defining a gem that is able to install itself as an /etc/init.d service on a debian machine.  My desired usage would be 

    generic_gem --type daemon gem_name

Which would go into a configuration directory, such as ~/.generic_gem/ and look for a folder named 'daemon' which would contain a gem's skeleton.  I'd strongly prefer to specify my own gem customizations (especially disabling licenses or opting for alternative licenses).  In a very clear manor so I don't have to worry about learning a new syntax or looking through any multi-page documentation.  

PS have you seen the way bundler creates generic files?  https://github.com/bundler/bundler/tree/master/lib/bundler/templates/newgem it might be worth having a look at what ever they're using to process .tt files and do something similar or perhaps use .erb which most people are already familiar with and comfortable with.

**Comment by jhsu802701** [comment]
I never thought about doing what you're suggesting.  I started this gem to fill in the details common to all/most gems I create that bundler doesn't take care of.  The configuration I use in GenericGem is in the style used by the most popular gem creation tutorials.  I prefer to do things by the book, because I usually get the best results.  The more I deviate from the mainstream way, the more I have to jump through hoops to get things to work, and the more difficulty I have finding help.
